/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.equipo7.proyecto1.ticketwizzard.dtos.BoletoDTO;
import com.equipo7.proyecto1.ticketwizzard.dtos.UsuarioDTO;
import java.sql.Date;
import javax.swing.BoxLayout;

/**
 *
 * @author neri
 */
public class BoletoUsuarioPanel extends javax.swing.JPanel {

    private BoletoDTO boleto;
    private UsuarioDTO usuario;
    
    /**
     * Creates new form BoletoEnVentaPanel
     * @param boleto
     * @param usuario
     */
    public BoletoUsuarioPanel(BoletoDTO boleto, UsuarioDTO usuario) {
        initComponents();
        this.boleto = boleto;
        this.usuario = usuario;
        this.setVisible(true);
        this.inicializar();
    }
    
    private void inicializar() {
        this.campoInfoAsiento.setText(this.boleto.getNumeroControl());
        this.campoFila.setText(this.boleto.getAsiento().getFila());
        this.campoNumeroAsiento.setText(this.boleto.getAsiento().getNumeroAsiento().toString());
        
        Date fechaLimite = this.boleto.getFechaLimiteVenta();
        if (fechaLimite != null) {
            this.campoFechaLimite.setText("Fecha Limite: " + fechaLimite.toString());
        } else {
            this.campoFechaLimite.setText("");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNumeroAsiento1 = new javax.swing.JLabel();
        campoInfoAsiento = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        campoFechaLimite = new javax.swing.JLabel();
        campoNumeroAsiento = new javax.swing.JLabel();
        campoFila = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(campoNumeroAsiento1, "Numero de asiento: X"); // NOI18N

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        campoInfoAsiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(campoInfoAsiento, "Numero Control"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label, "Numero de asiento: "); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lbl, "Fila:"); // NOI18N

        campoFechaLimite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(campoFechaLimite, "Fecha Limite: Fecha"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(campoNumeroAsiento, "NUMERO"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(campoFila, "FILA"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoInfoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(campoFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoFila, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNumeroAsiento)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFechaLimite)
                    .addComponent(campoInfoAsiento))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(campoNumeroAsiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(campoFila))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        frmVenderBoleto frm = new frmVenderBoleto(this.boleto, this.usuario);
        
        frm.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoFechaLimite;
    private javax.swing.JLabel campoFila;
    private javax.swing.JLabel campoInfoAsiento;
    private javax.swing.JLabel campoNumeroAsiento;
    private javax.swing.JLabel campoNumeroAsiento1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
