/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.equipo7.proyecto1.ticketwizzard.dtos.BoletoDTO;
import com.equipo7.proyecto1.ticketwizzard.dtos.UsuarioDTO;
import com.equipo7.proyecto1.ticketwizzard.excepciones.GestorException;
import com.equipo7.proyecto1.ticketwizzard.gestores.GestorBoletos;
import com.equipo7.proyecto1.ticketwizzard.interfaces.gestores.IGestorBoletos;
import java.sql.Date;

/**
 *
 * @author neri
 */
public class BoletoEnVentaPanel extends javax.swing.JPanel {

    private BoletoDTO boleto;
    private UsuarioDTO usuario;
    
    /**
     * Creates new form BoletoEnVentaPanel
     * @param boleto
     * @param usuario
     */
    public BoletoEnVentaPanel(BoletoDTO boleto, UsuarioDTO usuario) {
        initComponents();
        this.boleto = boleto;
        this.usuario = usuario;
        this.setVisible(true);
        this.inicializar();
    }

    private void inicializar() {
        this.campoInfoAsiento.setText(this.boleto.getNumeroControl());
        this.campoFila.setText(this.boleto.getAsiento().getFila());
        this.campoNumeroAsiento.setText(this.boleto.getAsiento().getNumeroAsiento().toString());

        
        Date fechaLimite = this.boleto.getFechaLimiteVenta();
        if (fechaLimite != null) {
            this.campoFechaLimite.setText("Fecha Limite: " + fechaLimite.toString());
        } else {
            this.campoFechaLimite.setText("");
        }
        
        
        
        // Mostrar el precio de reventa o el precio original
    if (this.boleto.getPrecioReventa() != null && this.boleto.getPrecioReventa() > 0) {
        this.campoPrecio.setText("Precio: " + this.boleto.getPrecioReventa().toString());
    } else {
        this.campoPrecio.setText("Precio: " + this.boleto.getPrecioOriginal().toString());
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoInfoAsiento = new javax.swing.JLabel();
        campoPrecio = new javax.swing.JLabel();
        btnComprarBoleto = new javax.swing.JButton();
        campoFechaLimite = new javax.swing.JLabel();
        campoNumeroAsiento = new javax.swing.JLabel();
        campoFila = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();

        campoInfoAsiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(campoInfoAsiento, "Numero Control"); // NOI18N

        campoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(campoPrecio, "Precio: $XXXX"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnComprarBoleto, "Comprar"); // NOI18N
        btnComprarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarBoletoActionPerformed(evt);
            }
        });

        campoFechaLimite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(campoFechaLimite, "Fecha Limite: Fecha"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(campoNumeroAsiento, "NUMERO"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(campoFila, "FILA"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label, "Numero de asiento: "); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lbl, "Fila:"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoInfoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(campoFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoFila, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNumeroAsiento)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFechaLimite)
                    .addComponent(campoInfoAsiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(campoNumeroAsiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(campoFila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrecio)
                    .addComponent(btnComprarBoleto))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBoletoActionPerformed
       try {
        // Obtener el gestor de boletos a través de la interfaz
        IGestorBoletos gestorBoletos = GestorBoletos.getInstance();

        // Verificar si el boleto está en venta
        if (!boleto.getEnVenta()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El boleto ya ha sido vendido.");
            return;
        }

        // Actualizar los datos del boleto
        boleto.setEnVenta(false);  // Marcar el boleto como vendido
        boleto.setIdUsuario(usuario.getId());  // Asignar el boleto al usuario actual

        // Llamar al gestor para actualizar el boleto
        gestorBoletos.actualizarBoleto(boleto);

        // Notificar al usuario que la compra fue exitosa
        javax.swing.JOptionPane.showMessageDialog(this, "Boleto comprado exitosamente!");

    } catch (GestorException e) {
        // Manejo de errores en caso de que algo salga mal con la compra
        javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar la compra del boleto: " + e.getMessage());
    }

    }//GEN-LAST:event_btnComprarBoletoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarBoleto;
    private javax.swing.JLabel campoFechaLimite;
    private javax.swing.JLabel campoFila;
    private javax.swing.JLabel campoInfoAsiento;
    private javax.swing.JLabel campoNumeroAsiento;
    private javax.swing.JLabel campoPrecio;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
