/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.equipo7.proyecto1.ticketwizzard.dtos.EventoDTO;
import com.equipo7.proyecto1.ticketwizzard.dtos.UsuarioDTO;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;

/**
 *
 * @author neri
 */
public class EventoPanel extends javax.swing.JPanel {

    private EventoDTO evento;
    private UsuarioDTO usuario;
    
    /**
     * Creates new form EventoPanel
     * @param evento
     * @param usuario
     */
    public EventoPanel(EventoDTO evento, UsuarioDTO usuario) {
        initComponents();
        this.evento = evento;
        this.setVisible(true);
        this.inicializar();
        this.usuario = usuario;
    }
    
    private void inicializar() {
        this.campoNombreEvento.setText(evento.getNombre());
        this.campoDescripcion.setText(evento.getDescripcion());
        this.campoFecha.setText(evento.getFechaHora().toString());
        this.campoCiudadEstado.setText(evento.getCiudad().getNombre() + ", " + evento.getCiudad().getEstado());
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNombreEvento = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JLabel();
        campoCiudadEstado = new javax.swing.JLabel();
        campoFecha = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(618, 100));
        setMinimumSize(new java.awt.Dimension(618, 100));
        setPreferredSize(new java.awt.Dimension(618, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        campoNombreEvento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(campoNombreEvento, "Nombre del Evento"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(campoDescripcion, "Descripcion"); // NOI18N

        campoCiudadEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(campoCiudadEstado, "Ciudad, Estado"); // NOI18N

        campoFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(campoFecha, "Fecha Evento"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCiudadEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                    .addComponent(campoFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCiudadEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(campoFecha)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         frmEvento frm = new frmEvento(this.evento, this.usuario);
         
         frm.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoCiudadEstado;
    private javax.swing.JLabel campoDescripcion;
    private javax.swing.JLabel campoFecha;
    private javax.swing.JLabel campoNombreEvento;
    // End of variables declaration//GEN-END:variables
}
