/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.equipo7.proyecto1.ticketwizzard.dtos.EventoDTO;
import com.equipo7.proyecto1.ticketwizzard.dtos.UsuarioDTO;
import com.equipo7.proyecto1.ticketwizzard.excepciones.GestorException;
import com.equipo7.proyecto1.ticketwizzard.gestores.GestorEventos;
import com.equipo7.proyecto1.ticketwizzard.interfaces.gestores.IGestorEventos;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author neri
 */
public class frmEventos extends javax.swing.JFrame {

    private UsuarioDTO usuario;
    private IGestorEventos eventos;

    public frmEventos(UsuarioDTO usuario) {
        initComponents();
        this.usuario = usuario;
        this.setVisible(true);
        this.eventos = GestorEventos.getInstance();
        this.inicializar();
    }
    
    private void inicializar() {
        this.campoNombreUsuario.setText(this.usuario.getNombreCompleto());
        this.listaEventos.setLayout(new BoxLayout(this.listaEventos, BoxLayout.Y_AXIS));
        this.cargarEventos();
    }
    
    private void cargarEventos()  {
        this.listaEventos.removeAll();
        
        try {
            for (EventoDTO evento: this.eventos.obtenerEventosTodos()) {
                System.out.println(evento);
                this.listaEventos.add(new EventoPanel(evento));
            }
        } catch (GestorException ex) {
            JOptionPane.showMessageDialog(
                    this, 
                    ex.getMessage(), 
                    "TicketWizzard - Eventos", 
                    JOptionPane.WARNING_MESSAGE
            );
        }
        
        this.listaEventos.revalidate();
        this.listaEventos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaEventos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaEventos.setMaximumSize(new java.awt.Dimension(620, 500));
        listaEventos.setMinimumSize(new java.awt.Dimension(620, 500));

        javax.swing.GroupLayout listaEventosLayout = new javax.swing.GroupLayout(listaEventos);
        listaEventos.setLayout(listaEventosLayout);
        listaEventosLayout.setHorizontalGroup(
            listaEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        listaEventosLayout.setVerticalGroup(
            listaEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaEventos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Eventos"); // NOI18N

        campoNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(campoNombreUsuario, "NombreUsuario"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoNombreUsuario)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoNombreUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaEventos;
    // End of variables declaration//GEN-END:variables
}
