
package gui;

import com.equipo7.proyecto1.ticketwizzard.dtos.BoletoDTO;
import com.equipo7.proyecto1.ticketwizzard.dtos.EventoDTO;
import com.equipo7.proyecto1.ticketwizzard.dtos.UsuarioDTO;
import com.equipo7.proyecto1.ticketwizzard.excepciones.GestorException;
import com.equipo7.proyecto1.ticketwizzard.gestores.GestorBoletos;
import com.equipo7.proyecto1.ticketwizzard.interfaces.gestores.IGestorBoletos;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author neri
 */
public class frmEvento extends javax.swing.JFrame {
    
    private final EventoDTO evento;
    private final UsuarioDTO usuario;
    
    private final IGestorBoletos boletos;
    
    /**
     * Creates new form frmEvento
     * @param evento
     * @param usuario
     */
    public frmEvento(EventoDTO evento, UsuarioDTO usuario) {
        initComponents();
        this.evento = evento;
        this.usuario = usuario;
        this.boletos = GestorBoletos.getInstance();
        this.inicializar();
    }
    
    private void inicializar() {
        this.campoNombre.setText(this.evento.getNombre());
        this.campoDescripcion.setText(this.evento.getDescripcion());
        this.campoDescripcion.setEditable(false);
        this.campoFechaEvento.setText(this.evento.getFechaHora().toLocalDate().format(DateTimeFormatter.ISO_DATE));
        this.listaBoletos.setLayout(new BoxLayout(this.listaBoletos, BoxLayout.Y_AXIS));
        this.setLocationRelativeTo(null);
        this.cargarBoletos();
    }
    
    private void volver() {
        // Crear la instancia de la nueva ventana
        frmEventos infoBoleto = new frmEventos(usuario);
        // Hacer visible la nueva ventana
        infoBoleto.setVisible(true);
        // Cerrar la ventana actual (frmBoletosEnVenta)
        this.dispose(); // 'this' hace referencia a la ventana actual
    }
    
    private void cargarBoletos() {
    
        this.listaBoletos.removeAll();
        
        try {
            List<BoletoDTO> boletos = this.boletos.obtenerBoletosVentaEvento(this.evento.getId());
            this.campoBoletosEncontrados.setText(""+boletos.size());
            
            for (BoletoDTO boleto: boletos) {
                this.listaBoletos.add(new BoletoEnVentaPanel(boleto, usuario));
            }
        } catch (GestorException ex) {
            JOptionPane.showMessageDialog(
                    this, 
                    ex.getMessage(), 
                    "TicketWizzard - Boletos", 
                    JOptionPane.WARNING_MESSAGE
            );
        }
        
        this.listaBoletos.revalidate();
        this.listaBoletos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaBoletos = new javax.swing.JPanel();
        campoNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoBoletosEncontrados = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        scrollpane = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        campoFechaEvento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaBoletosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout listaBoletosLayout = new javax.swing.GroupLayout(listaBoletos);
        listaBoletos.setLayout(listaBoletosLayout);
        listaBoletosLayout.setHorizontalGroup(
            listaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        listaBoletosLayout.setVerticalGroup(
            listaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaBoletos);

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(campoNombre, "Nombre del evento"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "Boletos Disponibles: "); // NOI18N

        campoBoletosEncontrados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(campoBoletosEncontrados, "100"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnVolver, "Volver"); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        scrollpane.setViewportView(campoDescripcion);

        campoFechaEvento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoFechaEvento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(campoFechaEvento, "fecha del evento"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoBoletosEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(campoFechaEvento))
                .addGap(30, 30, 30)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBoletosEncontrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaBoletosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaBoletosMouseClicked
        this.cargarBoletos();
    }//GEN-LAST:event_listaBoletosMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.volver();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel campoBoletosEncontrados;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JLabel campoFechaEvento;
    private javax.swing.JLabel campoNombre;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaBoletos;
    private javax.swing.JScrollPane scrollpane;
    // End of variables declaration//GEN-END:variables
}
