-- TODO: CREAR UNA VISTA PARA OBTENER LOS DATOS IMPORTANTES DEL BOLETO Y LOS DATOOS DE LA PRESENTACION JUNTO CON LA INFORMACION DEL EVENTO

-- TODO: CREAR UNA VISTA QUE TRAIGA TODOS LOS BOLETOS INVOLUCRADOS EN UNA
-- TRANSACCION DE LA TABLA transaccion_boleto




