/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.Admin;

import com.equipo7.proyecto1.ticketwizzard.dtos.CiudadDTO;
import com.equipo7.proyecto1.ticketwizzard.dtos.EventoDTO;
import com.equipo7.proyecto1.ticketwizzard.excepciones.GestorException;
import com.equipo7.proyecto1.ticketwizzard.gestores.GestorBoletos;
import com.equipo7.proyecto1.ticketwizzard.gestores.GestorCiudades;
import com.equipo7.proyecto1.ticketwizzard.gestores.GestorEventos;
import com.equipo7.proyecto1.ticketwizzard.interfaces.gestores.IGestorBoletos;
import com.equipo7.proyecto1.ticketwizzard.interfaces.gestores.IGestorEventos;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author caarl
 */
public class frmCrearEventos extends javax.swing.JFrame {

    private IGestorBoletos boletos;
    private IGestorEventos eventos;
    
    /**
     * Creates new form frmCrearEventos
     */
    public frmCrearEventos() {
        initComponents();
        this.boletos = GestorBoletos.getInstance();
        this.eventos = GestorEventos.getInstance();
        cargarCiudadesEnComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreEvento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcionEvento = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        DateChooserFechaHora = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtVenue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxCiudades = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregarEvento = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 8)); // NOI18N
        jLabel2.setText("Admin");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Crear Evento");

        jLabel1.setText("Nombre del evento:");

        jLabel4.setText("Descripcion del evento:");

        txtAreaDescripcionEvento.setColumns(20);
        txtAreaDescripcionEvento.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcionEvento);

        jLabel5.setText("Fecha y hora:");

        jLabel6.setText("Venue:");

        jLabel7.setText("Ciudad:");

        cbxCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCiudadesActionPerformed(evt);
            }
        });

        jLabel10.setText("Precio");

        btnAgregarEvento.setText("Agregar Evento");
        btnAgregarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEventoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(txtNombreEvento)
                                        .addComponent(txtVenue)
                                        .addComponent(DateChooserFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(125, 125, 125)
                                            .addComponent(btnAgregarEvento))
                                        .addComponent(btnCancelar))
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(242, 242, 242)
                    .addComponent(jLabel3)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateChooserFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEvento)
                    .addComponent(btnCancelar))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCiudadesActionPerformed

    private void btnAgregarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEventoActionPerformed
        try {
            // Capturar los datos del formulario
            String nombre = txtNombreEvento.getText();
            String descripcion = txtAreaDescripcionEvento.getText();
            Date fecha = new java.sql.Date(DateChooserFechaHora.getDate().getTime());
            String venue = txtVenue.getText();
            Float precioBoleto = Float.valueOf(txtPrecio.getText());
            boolean terminado = false;  // Valor predeterminado

            // Validar los campos
            if (nombre == null || nombre.trim().isEmpty()) {
                throw new Exception("El nombre del evento es obligatorio.");
            }
            if (descripcion == null || descripcion.trim().isEmpty()) {
                throw new Exception("La descripción del evento es obligatoria.");
            }
            if (venue == null || venue.trim().isEmpty()) {
                throw new Exception("El venue del evento es obligatorio.");
            }
            if (fecha == null) {
                throw new Exception("Seleccione una fecha válida.");
            }
            if (precioBoleto == null) {
                throw new Exception("El precio del boleto no es valido");
            }

            CiudadDTO ciudad = (CiudadDTO) cbxCiudades.getSelectedItem();
            if (ciudad == null || ciudad.getId() == null) {
                throw new GestorException("La ciudad seleccionada no tiene un ID válido.");
            } else {
                System.out.println("Ciudad seleccionada: " + ciudad.getId() + " - " + ciudad.getNombre());
            }

            // Crear el EventoDTO
            EventoDTO nuevoEvento = new EventoDTO();
            nuevoEvento.setNombre(nombre);
            nuevoEvento.setDescripcion(descripcion);
            nuevoEvento.setVenue(venue);
            nuevoEvento.setFechaHora(fecha);
            nuevoEvento.setTerminado(terminado); // Siempre false por ahora
            nuevoEvento.setCiudad(ciudad);
            nuevoEvento.setPrecioBaseBoleto(precioBoleto);

            System.out.println("Datos del evento: " + nuevoEvento.toString());

            // Llamar al gestor para agregar el evento
            this.eventos.agregarEvento(nuevoEvento);
            
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Evento agregado exitosamente.");

            // Limpiar los campos del formulario
            limpiarFormulario();

        } catch (Exception ex) {
            ex.printStackTrace();  // Imprimir la pila de errores en la consola
            JOptionPane.showMessageDialog(this, "Error al agregar evento: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarEventoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void limpiarFormulario() {
        txtNombreEvento.setText("");
        txtAreaDescripcionEvento.setText("");

        txtVenue.setText("");
        cbxCiudades.setSelectedIndex(-1);  // Opcional: dejar el combobox sin selección
    }

    private void cargarCiudadesEnComboBox() {
        try {
            // Limpia el ComboBox antes de agregar los elementos
            cbxCiudades.removeAllItems();

            // Obtener la lista de ciudades desde el gestor
            List<CiudadDTO> ciudades = GestorCiudades.getInstance().obtenerCiudadesTodas();

            // Verificar si la lista está vacía
            if (ciudades == null || ciudades.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron ciudades disponibles.");
                return;
            }

            // Agregar cada ciudad al ComboBox
            for (CiudadDTO ciudad : ciudades) {
                cbxCiudades.addItem(ciudad);
            }

        } catch (GestorException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar ciudades: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserFechaHora;
    private javax.swing.JButton btnAgregarEvento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<CiudadDTO> cbxCiudades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaDescripcionEvento;
    private javax.swing.JTextField txtNombreEvento;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
